steps:

# Build presto container image
- name: 'gcr.io/cloud-builders/docker'
  id: Build Presto
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/presto:${SHORT_SHA}', '--build-arg', 'presto_version=${_PRESTO_VERSION}', '-f', 'presto/Dockerfile', './' ]

# Push presto image to gcr 
- name: 'gcr.io/cloud-builders/docker'
  id: Push Presto
  args: [ 'push', 'gcr.io/$PROJECT_ID/presto:${SHORT_SHA}' ]

# Builds the presto cli 
- name: 'gcr.io/cloud-builders/docker'
  id: Build CLI
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/presto-cli:${SHORT_SHA}', '-f', 'presto-cli/Dockerfile', './' ]

# Push the cli image to gcr 
- name: 'gcr.io/cloud-builders/docker'
  id: Push CLI
  args: [ 'push', 'gcr.io/$PROJECT_ID/presto-cli:${SHORT_SHA}' ]

# Generate the manifests
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/PRESTO_IMAGE_URL/gcr.io\/$PROJECT_ID\/presto:${SHORT_SHA}/g" presto-common/manifests.k8s.tpl > _k8s.yml 

# Deploy the manifests 
- name: "gcr.io/cloud-builders/gke-deploy"
  id: Deploy
  args:
  - run
  - --filename=_k8s.yml
  - --location=us-central1-c
  - --cluster=cluster-1

# Validate the presto image using the cli 
- name: 'gcr.io/cloud-builders/docker'
  id: Validate
  args:
  - run
  - -e
  - server=35.238.175.52:80
  - gcr.io/$PROJECT_ID/presto-cli:${SHORT_SHA}

substitutions:
    _PRESTO_VERSION: 323-e.3

images:
- 'gcr.io/$PROJECT_ID/presto'
- 'gcr.io/$PROJECT_ID/presto-cli'
