steps:

# Validate the presto image using the cli 
- name: 'gcr.io/cloud-builders/docker'
  id: Validate
  args:
  - run
  - -e
  - server=35.238.175.52:80
  - gcr.io/presto-pl-gke/presto-cli:7ecb2aa

#- name: "gcr.io/cloud-builders/kubectl"
#  id: Validate
#  args:
#  - get
#  - po
#  - -n=presto
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

images:
- 'gcr.io/$PROJECT_ID/presto-cli'
